spring.application.name=blogapi

spring.data.web.pageable.one-indexed-parameters=true

server.port=8100
server.tomcat.uri-encoding=UTF-8
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=10
server.tomcat.threads.max-queue-capacity=2147483647
server.ssl.enabled=false

#session timeout \uC124\uC815
server.servlet.session.timeout=30m

spring.jpa.show-sql=true

spring.profiles.active=local

spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource
